### ISSUE TITLE
Error " Cannot set property 'language' of undefined"

### ISSUE THREAD

**Issue by charliehavak** [7Pass/gulp-pseudo-i18n#2]
Hi - running your example 

gulp.task('xx', function () {
    return gulp.src('./webapp/resources/translations/core.pot')
        .pipe(pseudo())
        .pipe(print())
        .pipe(gulp.dest('po/'));
});

I keep on getting the above error. Also when adding {language: 'qps-ploc'}

tnx
Charlie

**Comment by ngocvantran** [comment]
Can you please attach your core.pot file for me to reproduce the issue?

**Comment by charliehavak** [comment]
I just wrote a file with the string "hi there" in it - is it fine?

**Comment by ngocvantran** [comment]
No, it has to be a valid GNU Gettext POT file. See https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
